steps:
  - id: build-backend-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/${PROJECT_ID}/refex-engagement-report/backend-api:${COMMIT_SHA}
      - -f
      - services/backend-api/Dockerfile
      - .

images:
  - asia-south1-docker.pkg.dev/${PROJECT_ID}/refex-engagement-report/backend-api:${COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
